local spawn = require("common.enemy_spawn_patterns")

EnemySpawns = {}

spawn.append(EnemySpawns, spawn.zomb_chaos("zomb", 10, 0))
spawn.append(EnemySpawns, spawn.swarm("swarmer", 4, -210, 30, 50, 10, 5, 1.5))
spawn.append(EnemySpawns, spawn.swarm("swarmer", 4, 480, 700, 10, 60, 5, 1.5))
spawn.append(EnemySpawns, spawn.monitor_circle(12))
spawn.append(EnemySpawns, spawn.godsip_cardinal(12))
spawn.append(EnemySpawns, spawn.godsip_cardinal(18))
spawn.append(EnemySpawns, spawn.godsip_cardinal(24))
spawn.append(EnemySpawns, spawn.zomb_chaos("zomb", 5, 31, 0.6))
spawn.append(EnemySpawns, spawn.swarm("sniper", 5, 135, 10, 100, 150, 37))
spawn.append(EnemySpawns, spawn.swarm("sniper", 8, 730, 530, -50, -40, 45))
spawn.append(EnemySpawns, spawn.swarm("swarmer", 5, -110, -50, 15, 30, 53, 2.0))
spawn.append(EnemySpawns, spawn.zomb_chaos("zomb", 10, 60, 1.5))
spawn.append(EnemySpawns, spawn.godsip_cardinal(64))
spawn.append(EnemySpawns, spawn.godsip_cardinal(68))
spawn.append(EnemySpawns, spawn.godsip_cardinal(70))
spawn.append(EnemySpawns, spawn.swarm("swarmer", 24, -210, 30, 50, 10, 78, 1.5))
spawn.append(EnemySpawns, spawn.swarm("swarmer", 24, 480, 700, 10, 60, 78, 1.5))
spawn.append(EnemySpawns, spawn.godsip_cardinal(83))
spawn.append(EnemySpawns, spawn.godsip_cardinal(85))
spawn.append(EnemySpawns, spawn.godsip_cardinal(87))
spawn.append(EnemySpawns, spawn.godsip_cardinal(89))
spawn.append(EnemySpawns, spawn.godsip_cardinal(91))
spawn.append(EnemySpawns, spawn.monitor_circle(122))
spawn.append(EnemySpawns, spawn.godsip_cardinal(138))
spawn.append(EnemySpawns, spawn.zomb_chaos("zomb", 4, 145, 2.6))
spawn.append(EnemySpawns, spawn.monitor_circle(151))
spawn.append(EnemySpawns, spawn.godsip_cardinal(158))
spawn.append(EnemySpawns, spawn.godsip_cardinal(164))
spawn.append(EnemySpawns, spawn.swarm("sniper", 41, 0, 20, 20, 20, 167, 1.9))
spawn.append(EnemySpawns, spawn.zomb_chaos("zomb", 4, 169, 2.6))
